version: "3.0"

#Services to run

services:
  mongo_strategy: #name of BD service
    image: mongo
    container_name: class11_exercise2
    ports:
      - 27017:27017
    volumes:
      - mongostrategy:/dataconfigdb
      - mongostrategy:/data/dataconfigdb
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes: 
  mongostrategy:
