version: '3.8'

#Services to run
services:
  mongo_strategy: #Name of BD service
    image: mongo
    container_name: class12_eje1202
    ports:
      - 27017:27017
    volumes:
      - mongostrategyjwt:/data/configdb
      - mongostrategyjwt:/data/db
    restart: always 

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  mongostrategyjwt: