version: "3.8"

#Services to run

services:
  mongo_strategy: #name of BD service
    image: mongo
    container_name: class15_project2
    ports:
      - "27017:27017"
    volumes:
      - mongolayerarch:/data/configdb
      - mongolayerarch:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  mongolayerarch:
