version: "3.8"

#Services to run

services:
  mongo_strategy: #name of BD service
    image: mongo
    container_name: class15_project3
    ports:
      - 27017:27017
    volumes:
      - mongolayerarchlab1:/data/config
      - mongolayerarchlab1:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  mongolayerarchlab1:
