version: '3.8'

#Services to run
services:
  mongo_jwt: #Name of BD service 
    image: mongo
    container_name: class12-1201
    ports:
      - "27017:27017"
    volumes:
      - mongojwt2:/data/configdb
      - mongojwt2:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  mongojwt2: