version: '3.8'

#Services to run 
services:
  mongo_jwt: #name of BD service
    image: mongo
    container_name: class11_eje1103
    ports:
      - 27017:27017
    volumes:
      - mongojwt:/data/configdb
      - mongojwt:/data/db
    restart: always

networks:
  nodejs-network:
    name: nodejs-network
    driver: bridge

volumes:
  mongojwt: